---
title: Sati Plastics
timezone: Mumbai
collections:
  product categories:
    title: Product Categories
    output: false
  products:
    title: Products
    output: false
email: ashish@satiplastics.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: "/"
url: https://www.satiplastics.com
markdown: kramdown
exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"
sass:
  sass_dir: styles/
  style: compressed
