title: Sati Plastics
timezone: Mumbai

collections:
  product_categories:
    title: Product Categories
    output: false
  products:
    title: Products
    output: false

email: ashish@satiplastics.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.satiplastics.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

exclude:
- Gruntfile.js
- Gemfile
- Gemfile.lock
- package.json
- README*
- node_modules
- ".gitignore"

sass:
  sass_dir: styles/
  style: compressed
