backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "_uploads"
public_folder: "/uploads"
collections:
  - name: "product_categories"
    label: "Product Category"
    folder: "_products_categories"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
        required: false
  - name: "products"
    label: "Product"
    folder: "_products"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Image"
        name: "image"
        widget: "image"
      - label: "Product Category"
        name: "category"
        widget: "relation"
        collection: "product_categories"
        searchFields: "[title]"
        valueField: "title"
