backend:
  name: github
  repo: akshatkedia/satiplastics.com

media_folder: "_uploads"
public_folder: "/uploads"

collections:
  - name: "product"
    label: "Product"
    folder: "_products"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Product Code", name: "code", widget: "string"}
      - label: "Product Category"
        name: "category"
        widget: "relation"
        collection: "product_category"
        searchFields: ["title"]
        valueField: "title"
  - name: "product_category"
    label: "Product Category"
    folder: "_product_categories"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Image", name: "thumbnail", widget: "image"}
