---
label: Product category
hide_body: false
is_partial: false
fields:
- type: file
  name: featured_image
  label: Featured image
- type: field_group_list
  name: products
  label: Products
  fields:
  - type: file
    name: image
    label: Image
  - type: text
    name: name
    label: Name
pages:
- _product_categories/hdpe-bottles.md
- _product_categories/electrical.md
- _product_categories/caps-and-closures.md
- _product_categories/agriculture.md
