---
pages:
- _categories/sprays-and-pumps.md
- _categories/jars.md
- _categories/thread-spools.md
- _categories/measuring-cups-and-spoons.md
- _categories/bottles.md
hide_body: true
fields:
- type: file
  name: featured_image
  label: Featured Image
  config:
    maxSize: '0.5'
- type: field_group_list
  name: products
  label: Products
  fields:
  - type: text
    name: name
    label: Name
  - type: file
    name: image
    label: Image
